### ISSUE TITLE
NaN second-level statistics

### ISSUE THREAD

**Issue by effigies** [nistats/nistats#162]
To provide a brief context before diving in: I have a three-stage model. The initial contrast of one trial type vs others happens at the run level. I then contrast between two identical sessions, and the third level will be to take the intercept at the group level.

I am finding that at the second level - contrasting between sessions, I am getting a brainmask full of NaNs. I suspect what I'm doing wrong will be very obvious to you, but I've found nothing in the documentation to steer me right, so far.

-----

Consider the following first-level analysis:

```Python
import numpy as np
import nibabel as nb
from nistats import design_matrix as dm
from nistats import first_level_model as level1, second_level_model as level2

bold = "..."  # Preprocessed BOLD filename
brainmask = "..."  # Mask of BOLD series

# Trial types are "trial_type.Finger", "trial_type.Foot", "trial_type.Lips" in block design
paradigm = pd.DataFrame({'onset': [...], 'duration': [...], 'trial_type': [...])

img = nb.load(fname)
TR = img.header.get_zooms()[3]
vols = img.shape[3]

mat = dm.make_design_matrix(np.arange(vols) * TR, paradigm, drift_model=None)

fmri_glm = level1.FirstLevelModel(mask=brainmask)
fmri_glm.fit(bold.filename, design_matrices=mat)

conditions = ('trial_type.Finger', 'trial_type.Foot', 'trial_type.Lips')

indices = [mat.columns.get_loc(cond) for cond in conditions]

weights = np.zeros(len(mat.columns))
weights[indices] = [1, -0.5, -0.5]

stat = fmri_glm.compute_contrast(weights, 't')
stat.to_filename("...")
```

Now in a given subject, I'm going to contrast two identical sessions, so suppose I've run the above twice.

```Python
data = ["...",  # Session 1 filename (saved above)
        "..."]  # Session 2 filename (saved above)

paradigm = pd.DataFrame({'intercept': [1, 1], 'sessionDiff': [1, -1]})

fmri_glm = level2.SecondLevelModel()
fmri_glm.fit(data, design_matrix=paradigm)

stat = fmri_glm.compute_contrast('sessionDiff', second_level_stat_type='t')
```

Now if I look at `stat`, I see:

```Python
>>> np.unique(stat.get_data())
array([0., nan, nan, ..., nan, nan, nan])
```

I've verified that the `0`s are outside the brainmask, and the `nan`s within. I have also verified that the two input images are not identical.

I get the following warnings when running the `compute_contrast` above:

```
/data/cjmarkie/Projects/crn/nistats/nistats/regression.py:206: RuntimeWarning: divide by zero encountered in true_divide
  self.wdesign.shape[1])
/data/cjmarkie/Projects/crn/nistats/nistats/regression.py:206: RuntimeWarning: invalid value encountered in true_divide
  self.wdesign.shape[1])
/data/cjmarkie/Projects/crn/nistats/nistats/utils.py:206: RuntimeWarning: invalid value encountered in less_equal
  return np.where(X <= 0, 0, 1. / X)
/home/cjmarkie/.anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/home/cjmarkie/.anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/home/cjmarkie/.anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/home/cjmarkie/.anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1949: RuntimeWarning: invalid value encountered in greater
  cond1 = (0 < q) & (q < 1)
/home/cjmarkie/.anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1949: RuntimeWarning: invalid value encountered in less
  cond1 = (0 < q) & (q < 1)
```

**Comment by bthirion** [comment]
Hi @effigies 
Thx for reporting. My understanding is that at the second level, the definition of the design matrix saturates the model (2 regressors for 2 images), leading to 0 remaining degrees of freedom. Then the variance is 0 and the ensuing statistics (T, F, p_values) are not defined.
The point is that mixed effects are not yet properly handled in nistats, so that the model you propose ignores that the images come with a non-zero variance estimate.  

If your purpose is to compute a fixed effect of the first sessions -hence corresponding to the intercept of the design matrix, you can just give the two sessions to  your first level model, and will compute the first-level statistics across the two sessions. There is an example of this mechanism here https://github.com/nistats/nistats/blob/5745e7b6ffadc49b2c2b5c6948f4bb8a61bd7935/examples/02_first_level_models/plot_fiac_analysis.py#L58.

I have no solution for the other [1 -1] contrast. I have to say, I've never met this situation.
There is still a relatively pedestrian possibility, which ti to create manually the fixed effect and corresponding variance images manually
fixed_effect_img = session_2_effect_img - session_1_effect_img
fixed_variance_img = session_2_variance_img + session_1_variance_img

Note however that due to the limitation outlined above, the ensuing group analysis will not take into account the first-level variance estimate.

HTH

**Comment by effigies** [comment]
Alright, thanks for the explanation. This is basically a test model (working on an app to take BIDS models and run them through nistats), so it's more focused on exploring spec features than being a realistic implementation of a scientifically interesting model. If it becomes an actually common use case, then I can look into treating it as a special case and doing a manual calculation.

It would be handy if nistats could raise useful exceptions in cases like these, such as `ValueError("Saturated model")`. I can try to catch situations like this, myself, but I suspect the specific errors are going to map onto a smaller set of output conditions to check for.

One last question: Is it correct to pass to the second level model the images that were created from `compute_contrast()` with the default `output_type`? I'm a bit fuzzy on exactly when to specify an option.

**Comment by bthirion** [comment]
You mean, whether we should base second-level analysis on effect estimates, or t statistcis or their z-transform ?
I think that the third are acceptable. In general the first (effects estimate) is recommended (output_type='effect_size'). However, I often used z-maps.

**Comment by bthirion** [comment]
Can we close that one ?

**Comment by effigies** [comment]
Sure. Will reopen or open a new issue if I have further issues.
