### ISSUE TITLE
Failure in master with matplotlib 2.2.0

### ISSUE THREAD

**Issue by lesteve** [nistats/nistats#170]
`AttributeError: module 'matplotlib.cm' has no attribute 'spectral'`

See [Travis log](https://travis-ci.org/nistats/nistats/jobs/350542478).

Two possible short-term solutions:
* set `MATPLOTLIB_VERSION="2.1"` rather than `MATPLOTLIB_VERSION=*` in .travis.yml
* install nilearn master (where this problem has been fixed) via `pip install https://github.com/nilearn/nilearn`

**Comment by KamalakerDadi** [comment]
We will soon do a bugfix release of Nilearn. Will it be fine ?

**Comment by lesteve** [comment]
The nistats Travis build will be fixed as soon as you release nilearn with the fix I think.

**Comment by bthirion** [comment]
I think so. B


Sent from my smartphone. Sorry for misspelling and brevity.

-------- Message d'origine --------
De : KamalakerDadi <notifications@github.com> 
Date : 10/03/2018  11:16  (GMT+01:00) 
À : nistats/nistats <nistats@noreply.github.com> 
Cc : Subscribed <subscribed@noreply.github.com> 
Objet : Re: [nistats/nistats] Failure in master with matplotlib 2.2.0 (#170) 

We will soon do a bugfix release of Nilearn. Will it be fine ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nistats/nistats","title":"nistats/nistats","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nistats/nistats"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KamalakerDadi in #170: We will soon do a bugfix release of Nilearn. Will it be fine ?"}],"action":{"name":"View Issue","url":"https://github.com/nistats/nistats/issues/170#issuecomment-372019032"}}}

**Comment by KamalakerDadi** [comment]
Hi @lesteve We released Nilearn.

I just did git commit --amend to see if  the master is still failing. But, it is not. Should be fine now with recent matplotlib.

**Comment by KamalakerDadi** [comment]
Did this on the existing PR #163

**Comment by lesteve** [comment]
I have restarted the Travis build and it looks everything is fine indeed, closing, thanks a lot @KamalakerDadi!

**Comment by bthirion** [comment]
Thx ! B
