### ISSUE TITLE
Should accpet .tsv files as onset files

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#223]
Currently, the library assumes a csv format. Should actually use tsv. At least in a near future, should support both.
(PR #228 - KC)

**Comment by kchawla-pi** [comment]
Does it not already?
`pandas.from_csv()` seems to automatically figures out whether the separators/delimiters are tabs or commas and creates a pandas dataframe regardless. 
The functions in `nistats.first_level_model.py` have been coded to expect tsv, not csv. (they all use `pandas.from_csv(sep='\t')` not the default `sep=','` .
That csv is expected seems to be mentioned only in the documentation, not what is actually happening. Is that what needs fixing? Only the documentation?

**Comment by bthirion** [comment]
The small example  below triggers an error, because the paradigm file is not handled correctly
```
from nistats.first_level_model import FirstLevelModel
from nistats import datasets
data = datasets.fetch_localizer_first_level()
paradigm_file = data.paradigm
fmri_img = data.epi_img
first_level_model = FirstLevelModel(2.4, 0)
first_level_model = first_level_model.fit(fmri_img, paradigm_file)
```

**Comment by kchawla-pi** [comment]
The paradigm file in this example's data set is neither csv nor tsv, the values are separated by single spaces, not commas or tabs. How should we handle this?

**Comment by kchawla-pi** [comment]
> we should fix the csv file in the fetcher.
That would mean fixing the file and upload it to the online database, ftp.cea.fr .
How do we do that?

**Comment by bthirion** [comment]
I may find it, but this probably requires being on the CEA inrtanetwork. A hotfix is just to read and re-write the file after download ---in the fetcher function-- and return a correct file to the user.
Actually, we need to do that for all datasets fetched / imported / used in nistats. The experimental paradigm descriptors were set long before BIDS existed and should be trabsformed to regular BIDS onset files.

**Comment by kchawla-pi** [comment]
@KamalakerDadi 
nilearn._utils.numpy_conversions.csv_to_array managed to correctly load that file and may do so for several others.
We still will need a function to flag improper events file instead of transparently loading them.

**Comment by kchawla-pi** [comment]
@bthirion Even after the events file verify PR merge, the example you ave above still raises `ValueError: The provided paradigm has no onset key
`. I discovered this is because `utils._check_and_load_tables()` when reading the events file as a Pandas dataframe `pd.read_csv(table, index_col=0)`, is not reading the headers.

**Comment by bthirion** [comment]
Tes, but you're addressing it in PR #238

**Comment by kchawla-pi** [comment]
Yes, and that's what I am alluding to here. The events file is now BIDS compliant however the pandas.read_csv() is not reading those headers now. Earlier the problem was that there was no header, now it is that the header is tab-separated and the default separator read_csv expects is a comma.
At least I think that is the problem, but the function is reading the rest of the (tab-separated) data correctly, only messing with column names, which it is not reading at all, so that is weird.

I am going to try adding `sep='\t'` as the arg and check if it breaks anything. If it does, we may need to write a function to determine which separator is being used and then employ that to read the headers. That should be straightforward in itself. 
I am flummoxed why it is not reading headers at all while reading the remaining data correctly.

**Comment by kchawla-pi** [comment]
The argument `index_col=0` in the command `pd.read_csv(table, index_col=0)` in `utils._check_and_load_tables()` is creating the problem. For the `localizer_first_level` dataset, It is indicating the first column (which is `trial_type` data) as index (when there is no index), and also short-circuiting the code's ability to realize that the separator used in the file is a tab not a comma.
Technically, the correct function for reading tsv data is `pandas.read_table`, not `pandas.read_csv`.

**Comment by bthirion** [comment]
Sorry, but why not dropping this `index_col=0` ?

**Comment by kchawla-pi** [comment]
Mostly because I assume this was working fine long before I came along, and is malfunctioning only because we are now living in a Tabs-first world. This may be what the older events.csv files might need to load properly.
I am pushing a commit that reads using tabs and if the dataframe is empty, uses this command to load it instead.

**Comment by bthirion** [comment]
I believe as did that as a hack to make the code work on poorly defined events matrices. I don't want to keep such crap in the codebase. Also, i'm not a pandas expert and certainly does very awkward manipulations.

**Comment by kchawla-pi** [comment]
I believe 3 tests are failing without this workaround. We can either modify the test files in those cases or attend to this post-tutorial. What would you like?

**Comment by bthirion** [comment]
OK, I may be a bit lost now. I thout that in one of the open PRs we were rewriting the old onset files to make them BIDS compliants ('\t', with 'duration' etc.), making this superfluous. I need to check.

**Comment by kchawla-pi** [comment]
The dataset fetchers will be BIDS compliant, but nosetests fail due to generated files I think. I didn't take a deep look at them, yet.
