### ISSUE TITLE
How to interpret labels and estimates returned from run_glm?

### ISSUE THREAD

**Issue by dangom** [nistats/nistats#401]
If I [run a glm](https://nistats.github.io/modules/generated/nistats.first_level_model.run_glm.html#nistats.first_level_model.run_glm) a get labels and estimates. What do their numbers mean and how do I interpret the regression results?

```python
 In [168] labels
Out [168] array([0.83, 0.82, 0.77, 0.86, 0.89, 0.91, 0.9 , 0.92, 0.92, 0.92, 0.92,
                 0.92, 0.92, 0.92, 0.92, 0.92, 0.91, 0.9 , 0.89, 0.87, 0.85, 0.8 ,
                 0.83, 0.86, 0.86, 0.89, 0.9 , 0.92, 0.92, 0.92, 0.91, 0.92, 0.92,
                 0.92, 0.92, 0.92, 0.91, 0.89, 0.9 , 0.86])

 In [169] estimates
Out [169] {0.77: <nistats.regression.RegressionResults at 0x145e38320>,
           0.8: <nistats.regression.RegressionResults at 0x159164d68>,
           0.82: <nistats.regression.RegressionResults at 0x1591641d0>,
           0.83: <nistats.regression.RegressionResults at 0x159164668>,
           0.85: <nistats.regression.RegressionResults at 0x159164fd0>,
           0.86: <nistats.regression.RegressionResults at 0x1591640b8>,
           0.87: <nistats.regression.RegressionResults at 0x1591647f0>,
           0.89: <nistats.regression.RegressionResults at 0x159164940>,
           0.9: <nistats.regression.RegressionResults at 0x159164048>,
           0.91: <nistats.regression.RegressionResults at 0x159164160>,
           0.92: <nistats.regression.RegressionResults at 0x1591645c0>}
```

**Comment by bthirion** [comment]
Dear dangom,

Maybe this discussin would be better on Neurostars.
run_glm is a low-level function: obviously its ouptut is not meant to be dealt with directly. We only used it in nistats atm because there's no high-level function to deal with surface-based GLM (we this we need a Surfacemasker object in nilearn that is not there yet).

glms are indexed by the noise model. More precisely, we use the AR(1) coefficients of models residuls to group the voxels into classes. For each class, the whitening procedure, hence the AR(1) GLM computations are fixed.

hence, for each for this labels, you obtain a   RegressionResults that exactly yields the summary statistics you need for contrast computations.

These things have to be given to a function that will perform contrast handling --as in the surface-based GLM example. 

Does that make sense ? I agree that this is ugly and hacky.

**Comment by dangom** [comment]
Thanks bthirion. That makes sense.

As in the [example](https://nistats.github.io/auto_examples/02_first_level_models/plot_localizer_surface_analysis.html#sphx-glr-auto-examples-02-first-level-models-plot-localizer-surface-analysis-py) given in the documentation,  I noticed I can get the betas I'm after by running:

```python
con = compute_contrast(labels, estimates, contrast_val, contrast_type="t")
con.effect
```
But I guess end-users shouldn't be using either `run_glm` nor `compute_contrast` directly, as you say.  I'll close this issue and reopen a discussion in neurostats if I have other questions. As always, thanks for sharing the project and for the quick response.

**Comment by jeromedockes** [comment]
> run_glm is a low-level function: obviously its ouptut is not meant to be dealt with directly. We only used it in nistats atm because there's no high-level function to deal with surface-based GLM (we this we need a Surfacemasker object in nilearn that is not there yet).
>

Is this something that we should consider? Indeed very little 
would be required to allow this example to use FirstLevelModel instead
of the low-level functions.

**Comment by bthirion** [comment]
We should consider this, but this has to rely on a proper SurfaceMasker I guess.

**Comment by kchawla-pi** [comment]
Let's spec it out, what all do we need to implement a SurfaceMasker in a new issue in Nilearn. Whenever we decide to work on it, it'll be a good document to start at.

**Comment by jeromedockes** [comment]
> We should consider this, but this has to rely on a proper SurfaceMasker I guess.

would that masker map from volume to surface? (but what would be the inverse_transform?)
or should we add proper support for surface data in nilearn (but the
nibabel documentation for Gifti images is somewhat cryptic)?

**Comment by bthirion** [comment]
I mean the second one: add proper support for surface data in nilearn.
