### ISSUE TITLE
Maps threshold bug

### ISSUE THREAD

**Issue by BTajini** [nistats/nistats#444]
Hi,

I believe there's a bug in the maps threshold.
As you can see in the following screenshot.

![maps_threshold_bug](https://user-images.githubusercontent.com/24271712/76543384-bc8d6600-6486-11ea-83f8-9f48c53fdc7c.png)

 In the t_stats , we have some negative zones while in Raw z map, they are positive.

Best,

**Comment by bthirion** [comment]
Can you send me the code you used ? I can't reproduce the issue.

**Comment by bthirion** [comment]
OK, the problem comes from the fact that you obtained the p-values from a ttest_onesamp of scipy.stats that is a two-sided tests, and implicitly takes the absolute value.
You should use nistats functions, not ttest_onesamp, in that context (copy-pasting from old notebooks has some drawbacks !).
Best,
