### ISSUE TITLE
make orthogonalization of regressors optional

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#92]
I think it is not always desirable to orthogonalize. I myself wanted to avoid it in a current analysis where some multicollinearity was added purposefully. Moreover I think its an operation that do not belong to hemodynamic_models but to design_matrix creation.

I propose to take the orthogonalization out of the compute_regressor function in hemodynamic_models.py and make it an explicit option in make_design_matrix in design_matrix.py

**Comment by MartinPerez** [comment]
SPM and FSL have different policies about this, which is another reason I would keep this optional.
Moreover I think this paper can add something to the discussion
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0126255

**Comment by bthirion** [comment]
I think there is a misunderstanding here: the othogonalization that is performed in hemodynamic_models.py concerns the time and dispersion derivatives of the hrf, not the main regressors. I think that I am against any kind of systematic orthogonalization of design matrix columns, but I don't see reasons not to it with the hrf (note that by construction these regressors should be approximately orthogonal).

There is one think that we have not implemented yet: namely the orthogonalization of "confounds" wrt the main regressors. I'm not sure whether this is a useful feature.

**Comment by chrplr** [comment]
I agree with Bertrand  ("against any kind of systematic orthogonalization of design matrix columns" & not an issue with hrf and its derivatives).  

About "the orthogonalization of "confounds" wrt the main regressors. I'm not sure whether this is a useful feature.", I also think that if we think of confounds as confounds we do not want to orthogonalize them wrt the main regressors.
 
But can't we think of cases where 'confounds' are variables of non-interest that are put in the model to improve the fit over the model with just the variables of interest (I am thinking about physiological variables for example). If think it is good idea to have a function to explicitly orthogonlise a set a variables against another set, so that the user would be very conscious of what s/he is doing. I do not like the SPM automatic orthognosalization of parametric regressors and had to disable it many times.

**Comment by bthirion** [comment]
I think I like your suggestion of confounds variables wrt the main variables optional.
Also, plotting the correlation structure induced by the design matrix would be a desirable feature, to more easily introspect models.

**Comment by bthirion** [comment]
See #241. Closing that one.
